name: covid19tracker
description: A flutter application that tracks there amount of people sick from the Coronavirus

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  http: ^0.12.1
  provider: ^4.0.4
  curved_navigation_bar: ^0.3.2


dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true

  assets:
    - assets/

